"""empty message

Revision ID: 49667ac7bc97
Revises: d0d8645adafb
Create Date: 2022-08-17 15:57:41.150940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49667ac7bc97'
down_revision = 'd0d8645adafb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
