"""empty message

Revision ID: 76c2ace405c1
Revises: d921092328e5
Create Date: 2022-08-15 19:35:26.728856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c2ace405c1'
down_revision = 'd921092328e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=120)))
    op.drop_column('artists', 'description')
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=120)))
    op.drop_column('venues', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('venues', 'seeking_description')
    op.add_column('artists', sa.Column('description', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
