"""empty message

Revision ID: d0d8645adafb
Revises: 76c2ace405c1
Create Date: 2022-08-17 07:33:56.243712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d8645adafb'
down_revision = '76c2ace405c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'looking_for_venues',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('venues', sa.Column('genres', sa.String(length=120), nullable=True))
    op.alter_column('venues', 'looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'looking_for_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('venues', 'genres')
    op.alter_column('artists', 'looking_for_venues',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
